spring:
  application:
    name: Rentify

  #we choose active profile
  profiles:
    active: dev

  # Liquibase configuration
  liquibase:
    change-log: classpath:liquibase/master.xml

jwt:
  secret:  bjskdbvojbdvBVOUbdvjdbVodbvubdVUObdJBVueBosjVBweuVOIEWVBVBNOEWIVGUEGGGggsvbdvdjVWIOEVBOEIvsbvsjbdieuvhe
  validityInMinutes: 43200 #vrati na 15
  refreshValidityInMinutes: 43200 # 30 days