spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentify?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CET&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    multipart:

  jpa:
    show-sql: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

server:
  port: 8080