spring:
  application:
    name: Rentify
  profiles: #we choose active profile
    active: dev

jwt:
  secret:  bjskdbvojbdvBVOUbdvjdbVodbvubdVUObdJBVueBosjVBweuVOIEWVBVBNOEWIVGUEGGGggsvbdvdjVWIOEVBOEIvsbvsjbdieuvhe
  validityInMinutes: 15
  refreshValidityInMinutes: 2880 #48h
