spring:
  application:
    name: Rentify

  # we set active profile
  profiles:
    active: dev

  # Liquibase configuration
  liquibase:
    change-log: classpath:liquibase/master.xml

  # maximum allowed size for images
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # email configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: jovanvukovic09@gmail.com
    password: ctrnwzthugudhizm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret:  bjskdbvojbdvBVOUbdvjdbVodbvubdVUObdJBVueBosjVBweuVOIEWVBVBNOEWIVGUEGGGggsvbdvdjVWIOEVBOEIvsbvsjbdieuvhe
  validityInMinutes: 43200 #vrati na 15min
  refreshValidityInMinutes: 43200 # 30days